### ISSUE TITLE
Implementar parte visual

### ISSUE THREAD

**Issue by Funnick** [Funnick/Proyecto_ia-sim-cmp#7]
Algo lindo pero sencillo

**Comment by Funnick** [comment]
La idea aquí es visualizar las variables que vamos a tener en la simulación como si estuvieramos en Estadística, con gráficas y tablas.

**Comment by manuelAW99** [comment]
Sí, vamos a hacerlo con streamlit, plotlib y la simulación con pygame. Estoy en ello 👍
